### ISSUE TITLE
Adding mixin to the alias?

### ISSUE THREAD

**Issue by andre-nguyen** [colcon/colcon-alias#9]
I'm trying to register an alias to run build with a mixin e.g.
```
colcon build --mixin release
```
however running
```
$ colcon alias build_release --command build --mixin release
```
produces
```
colcon: error: Mixin 'release' is not available for 'alias'
```

I can get around the error by putting the mixin in quotes
```
$ colcon alias build_release --command build "--mixin release"
Registered command list for alias 'build_release':
  build --mixin release
```
however this produced an error when calling the alias:
```
$ colcon build_release
colcon: error: unrecognized arguments: --mixin release
```

Any way around this or is this expected behavior?

**Comment by cottsay** [comment]
Ooh, tricky. Yeah, this is a bug. I'll have to put some thought into how we might get around this.

**Comment by christophebedard** [comment]
Maybe make `--command` expect a simple string instead of an array and then call `shlex.split()` internally?

**Comment by cottsay** [comment]
I think the best move is to block mixin injection for the entire 'alias' verb. Please give #10 a try and provide feedback there.
